/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

/**
 *
 * @author ajithabh krishna
 */
public class Emergency extends javax.swing.JFrame {

    /**
     * Creates new form Emergency
     */
    public Emergency() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Select Your Emergency");

        jButton1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Cardiac Arrest / No Breathing");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 255));
        jButton4.setText("Choke");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 255));
        jButton6.setText("Bleeding");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 255));
        jButton10.setText("Burns");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 0, 51));
        jButton9.setText("Back");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel2.setText("Emergency not found?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(209, 209, 209))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        emerge em=new emerge();
        em.jTextArea1.setText("Assess the situation: Check the area for any potential hazards or risks. Ensure your safety and the safety of the victim before approaching them.\n" +
"\n" +
"1. Check for responsiveness: Tap the victim's shoulder and shout loudly, \"Are you okay?\" If they don't respond, it indicates a medical emergency.\n" +
"\n" +
"2. Call for help: If there are other people around, ask someone to call emergency services (such as 911) or activate the local emergency response system. Provide clear and specific details about the situation and the victim's condition.\n" +
"\n" +
"3. Position the victim: Gently place the victim on their back on a firm surface. If you suspect a spinal injury, use extreme caution while moving the person and try to keep their head and neck aligned.\n" +
"\n" +
"4. Open the airway: Tilt the victim's head back slightly and lift the chin to open their airway. This helps ensure proper airflow during rescue breaths.\n" +
"\n" +
"5. Check for breathing: Look, listen, and feel for breathing. Place your ear near their mouth, watch for chest movements, and feel for breath on your cheek. If the person is not breathing or is only gasping, it indicates the need for CPR.\n" +
"\n" +
"6. Begin chest compressions: Position the heel of one hand on the center of the victim's chest, slightly above the lower half of the breastbone. Place your other hand on top of the first hand. Interlock your fingers and keep your arms straight.\n" +
"\n" +
"7. Compress the chest: Push hard and fast in the center of the chest, aiming for a depth of at least 2 inches (5 cm). Allow the chest to fully recoil between compressions, but try to maintain a consistent tempo of approximately 100-120 compressions per minute.\n" +
"\n" +
"8. Perform rescue breaths: After 30 compressions, give two rescue breaths. Ensure the victim's airway is open, pinch their nose shut, and make a complete seal over their mouth with yours. Deliver a breath for about 1 second, watching for chest rise. Repeat the breath once more.\n" +
"\n" +
"9. Continue cycles of compressions and breaths: Perform a cycle of 30 chest compressions followed by 2 rescue breaths. Continue these cycles until:\n" +
"\n" +
"The victim shows signs of life, such as breathing.\n" +
"An automated external defibrillator (AED) becomes available and can be used.\n" +
"Trained medical personnel take over.\n" +
"You are too exhausted to continue.");
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        this.dispose();
        Home spec=new Home();
        spec.setLocationRelativeTo(null);
        spec.setVisible(true);
        spec.pack();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        emerge em2=new emerge();
        em2.jTextArea1.setText("Minor bleeding\n" +
" Small cuts and abrasions that are not bleeding excessively can be managed at home. First aid suggestions include:\n" +
"\n" +
"* Clean the injured area with sterile gauze soaked in normal saline or clean water. Do not use cotton wool or any material that will fray or leave fluff in the wound.\n" +
"* Apply an appropriate dressing such as a band aid or a non-adhesive dressing held in place with a hypoallergenic tape. This dressing must be changed regularly.\n" +
"* See your doctor if you can’t remove the dirt yourself. A dirty wound carries a high risk of infection.\n" +
"* If you have not had a booster vaccine against tetanus in the last five years, see your doctor."+ "\n"
                + "\n"
                + "Nosebleeds\n" +
"Bleeding from the nose is usually not severe. First aid suggestions include:\n" +
"\n" +
"* Sit the person upright and ask them to tilt their head forward.\n" +
"* Using the thumb and forefinger, squeeze their nostrils shut.\n" +
"* Hold for at least 10 minutes.\n" +
"* Release the hold gently and check for bleeding. If the bleeding has stopped, advise them to avoid blowing their nose or picking at it for the rest of the day.\n" +
"* If the bleeding continues beyond 20 minutes, seek medical aid.\n" +
"* If the nose bleed occurs again, seek medical aid.");
        em2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
         emerge em=new emerge();
        em.jTextArea1.setText("To carry out a back blow on an adult:\n" +
"\n" +
"* Stand behind them and slightly to one side. Support their chest with 1 hand. Lean them forward so the object blocking their airway will come out of their mouth, rather than moving further down.\n" +
"* Give up to 5 sharp blows between their shoulder blades with the heel of your hand. The heel is between the palm of your hand and your wrist.\n" +
"* Check if the blockage has cleared.\n" +
"If not, give up to 5 abdominal thrusts.");
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       emerge em=new emerge();
       em.jTextArea1.setText("Treating major burns\n" +
"Until emergency help arrives:\n" +
"\n" +
"*  Protect the burned person from further harm - If you can do so safely, make sure the person you're helping is not in contact with the source of the burn. For electrical burns, make sure the power source is off before you approach the burned person. Don't try to remove clothing stuck in the burn.\n" +
"* Make certain that the person burned is breathing - If needed, begin rescue breathing if you know how.\n" +
"* Remove jewelry, belts and other tight items, especially from the burned area and the neck. Burned areas swell quickly.\n" +
"* Cover the burn. Loosely cover the area with gauze or a clean cloth.\n" +
"* Raise the burned area. Lift the wound above heart level if possible.\n" +
"* Watch for signs of shock. Signs and symptoms include cool, clammy skin, weak pulse and shallow breathing."
               + "\n"
               + "Treating minor burns\n" +
"For minor burns:\n" +
"\n" +
"* Cool the burn - Hold the area under cool (not cold) running water for about 10 minutes. If the burn is on the face, apply a cool, wet cloth until the pain eases. For a mouth burn from hot food or drink, put a piece of ice in the mouth for a few minutes.\n" +
"* Remove rings or other tight items from the burned area - Try to do this quickly and gently, before the area swells.\n" +
"* Don't break blisters - Blisters help protect against infection. If a blister does break, gently clean the area with water and apply an antibiotic ointment.\n" +
"* Apply lotion - After the burn is cooled, apply a lotion, such as one with aloe vera or cocoa butter. This helps prevent drying and provides relief.\n" +
"* Bandage the burn - Cover the burn with a clean bandage. Wrap it loosely to avoid putting pressure on burned skin. Bandaging keeps air off the area, reduces pain and protects blistered skin.\n" +
"* If needed, take a nonprescription pain reliever, such as ibuprofen (Advil, Motrin IB, others), naproxen sodium (Aleve) or acetaminophen (Tylenol, others).");
       em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        //this.dispose();
        new NewEmerg().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emergency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
