package javaapplication2;
import javax.swing.*;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ajithabh krishna
 */

public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        this.setSize(597,346);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        label2.setText("label2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(357, 369));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel7.setText("Select Your Symptom");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cough", "Cold", "Acidity", "Constipation", "Nausea", "Diarrhea", "Malaria", " " }));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search For Solutions");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cannot Find Your Symptom?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addGap(52, 52, 52)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a;
        a = jComboBox1.getSelectedItem().toString();
        
        if (a== "Cough")
        {   //JFrame newWindow=new JFrame();
            //JTextArea textArea=new JTextArea("lorem ipsum");
            //textArea.setSize(500,300);
            //newWindow.setSize(1000,600);
            //JButton btn=new JButton();
            //newWindow.add(textArea);
            
            remedies remed=new remedies();
            remed.remedtext.setText("1. Using Hot fluids to drink like soup, broth, warm water \n2. Turmeric\n3.  Ginger can be consumed as a tea.\n4. Peppermint\n5.Humidifier\n6.Salt Water Gargling");
            remed.setVisible(true);
            
            
            //jTextArea1.setText("1. Honey \n2. Turmeric\n3. Ginger\n4. Peppermint\n5.Humidifier\n6.Salt Water Gargling");
            //jTextArea2.setText("no input ");
        }
        else if (a=="Cold"){
            remedies remed=new remedies();
            remed.remedtext.setText("1.  Drinking honey in tea with lemon \n2. Take plenty of water\n3. Make tea by simmering a few slices of raw ginger root in boiling water\n4. Use saline nasal drops and sprays.\n5.Humidifier\n6.Salt Water Gargling");
            remed.setVisible(true);
            //jTextArea1.setText("1. Honey \n2. Take plenty of water\n3. Ginger\n4. Use saline nasal drops and sprays.\n5.Humidifier\n6.Salt Water Gargling");
        }
        else if(a=="Diarrhea"){
            remedies remed=new remedies();
            remed.remedtext.setText("1. Hydration \n2. Having Probiotics\n3. Use Ginger\n");
            remed.setVisible(true);
            //jTextArea1.setText("1. Hydration \n2. Probiotics\n3. Ginger\n");
        }
        else if(a=="Nausea"){
             remedies remed=new remedies();
            remed.remedtext.setText("1. Ginger can also be consumed as a tea. \n2.Avoid Carbonated Drinks\n3.Stay Hydrated\n4. Using Peppermint\n5.Avoid Spicy Food\n6. Using Cinnamon");
            remed.setVisible(true);
            //jTextArea1.setText("1.Ginger \n2.Avoid Carbonated Drinks\n3.Stay Hydrated\n4. Peppermint\n5.Avoid Spicy Food\n6.Cinnamon");
        }
        else if(a=="Constipation"){
             remedies remed=new remedies();
            remed.remedtext.setText("1.Drink more water\n2. Probiotic foods\n3.Try avoiding dairy\n4.Take a fiber supplement\n5.Get some exercise");
            remed.setVisible(true);
            //jTextArea1.setText("1.Drink more water\n2. Probiotic foods\n3.Try avoiding dairy\n4.Take a fiber supplement\n5.Get some exercise");
        }
        else if(a=="Acidity"){
             remedies remed=new remedies();
            remed.remedtext.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
            remed.setVisible(true);
            //jTextArea1.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
        }
        else if(a=="Malaria"){
             remedies remed=new remedies();
            remed.remedtext.setText("1 - Apple Vinegar–\n" +
"\n" +
"Apple Cider Vinegar mixed with water, soaked in a towel and kept on calves for 10-12 minutes.\n" +
"\n" +
"2 - Ginger Water–\n" +
"\n" +
"Boil ginger in water and drink 1-2 cups on a daily basis.\n" +
"\n" +
"3 - Cinnamon and Honey Water–\n" +
"\n" +
"Boil cinnamon and pepper powder in water. Add honey to the strained water and drink it 1-2 times a day.\n" +
"\n" +
"4 - Fresh Juice–\n" +
"\n" +
"Consume 2-3 glasses of orange juice, sweet lime juice or grapefruit juice on a daily basis.\n" +
"\n" +
"5 - Herbal Tea and Milk–\n" +
"\n" +
"Have 2 cups of herbal tea or turmeric milk every day.");
            remed.setVisible(true);
           
            //jTextArea1.setText("1 - Apple Vinegar\n2 - Ginger Water\n3 - Cinnamon and Honey Water\n4 - Fresh Juice–\n5.Apple cidar vinegar");
        }
        else if(a=="Malaria"){
            //jTextArea1.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
        }
        else if(a=="Malaria"){
            //jTextArea1.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
        }
        else if(a=="Malaria"){
            //jTextArea1.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
        }
        else if(a=="Malaria"){
            //jTextArea1.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
        }
        else if(a=="Malaria"){
            //jTextArea1.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
        }
        else if(a=="Malaria"){
            //jTextArea1.setText("1.Fennel/Saunf\n2.Black cumin seeds\n3.Watermelon Juice\n4.Lukewarm water\n5.Apple cidar vinegar");
        }
        else  {
            //jTextArea1.setText("gargling....natural remdiess list for cough.. ");
            //jTextArea2.setText("medicines list for cough.. ");
        }   
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Home().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    new NewSymp().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
